### ISSUE TITLE
How to load the trained parameters which are saved in .pkl?

### ISSUE THREAD

**Issue by hanxue2017** [sisl/MADRL#11]
I use 
file=open('/Users/xuehan/MADRL/data/experiment_2017_11_03_15_34_27_439853_CST_7fbba/itr_0.pkl','rb')   inf =joblib.load(file)  file.close() to load trained parameters but has errors. Hopes you can tell me how to successfully load the trained parameters!
Traceback (most recent call last):
  File "run_multiwalker.py", line 60, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "run_multiwalker.py", line 54, in main
    run(curr)
  File "/Users/xuehan/MADRL/runners/rurllab.py", line 395, in __call__
    env, policy = rllab_envpolicy_parser(self.env, self.args)
  File "/Users/xuehan/MADRL/runners/rurllab.py", line 185, in rllab_envpolicy_parser
    min_std=args.min_std, name='policy')
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/site-packages/sandbox/rocky/tf/policies/gaussian_mlp_policy.py", line 105, in __init__
    inf =joblib.load(file)       #读取pkl文件的内容
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 443, in load
    with open(filename, 'rb') as file_handle:
TypeError: invalid file: <_io.BufferedReader name='/Users/xuehan/MADRL/data/experiment_2017_11_03_15_34_27_439853_CST_7fbba/itr_0.pkl'>

**Comment by rejuvyesh** [comment]
[`joblib.load`](https://pythonhosted.org/joblib/generated/joblib.load.html) directly takes the file name.

**Comment by hanxue2017** [comment]
I directly use inf=joblib.load('/Users/xuehan/MADRL/data/experiment_2017_12_01_11_02_45_913858_CST_b9092/itr_0.pkl'),but it also has an error:
Traceback (most recent call last):
  File "run_multiwalker.py", line 60, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "run_multiwalker.py", line 54, in main
    run(curr)
  File "/Users/xuehan/MADRL/runners/rurllab.py", line 394, in __call__
    env, policy,information= rllab_envpolicy_parser(self.env, self.args)
  File "/Users/xuehan/MADRL/runners/rurllab.py", line 51, in rllab_envpolicy_parser
    inf=joblib.load('/Users/xuehan/MADRL/data/experiment_2017_12_01_11_02_45_913858_CST_b9092/itr_0.pkl')
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 459, in load
    obj = unpickler.load()
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 316, in load_build
    Unpickler.load_build(self)
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/pickle.py", line 1510, in load_build
    setstate(state)
  File "/Users/xuehan/anaconda/envs/rllab3/lib/python3.5/site-packages/sandbox/rocky/tf/core/parameterized.py", line 98, in __setstate__
    tf.get_default_session().run(tf.initialize_variables(self.get_params()))
AttributeError: 'NoneType' object has no attribute 'run'

**Comment by hanxue2017** [comment]
Thank you very much!






At 2017-12-01 14:42:56, "Jayesh K. Gupta" <notifications@github.com> wrote:


You have to do this inside a a tensorflow session:

with tf.Session() as sess:
    joblib.load(...)

**Comment by hanxue2017** [comment]
Thank you very much!
