### ISSUE TITLE
proxy.client("set_state", state_str, async=True) error while running code

### ISSUE THREAD

**Issue by anirudhajitani** [sisl/MADRL#18]
When I try to clone the repo using recursive command, I get the following errors:
git clone --recursive git@github.com:sisl/MADRL.git
Cloning into 'MADRL'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Therefore, I cloned only this repo and cloned the rllab and rltools repo manually and added them to the PYTHONPATH as mentioned. I also installed all depenedencies from environment.yml in rllab.

However, when I run the command:
python3 runners/run_multiwalker.py rllab --control decentralized --policy_hidden 100,50,25  --n_iter 200  --n_walkers 2  --batch_size 24000  --curriculum lessons/multiwalker/env.yaml

I get the following errors:
Traceback (most recent call last):
  File "runners/run_multiwalker.py", line 10, in <module>
    from madrl_environments.walker.multi_walker import MultiWalkerEnv
  File "/Users/anirudhajitani/Downloads/Projects/MADRL/madrl_environments/__init__.py", line 1, in <module>
    from rltools.util import EzPickle, stack_dict_list
  File "/Users/anirudhajitani/Downloads/Projects/MADRL/rltools/rltools/util.py", line 157
    proxy.client("set_state", state_str, async=True)
                                             ^
SyntaxError: invalid syntax

I tried to find the the function client, but the prototype for it is completely different. Can somebody tell me what I am foing wrong?

**Comment by rejuvyesh** [comment]
You need to `git checkout` the correct commit as you would get by recursive clone.

**Comment by anirudhajitani** [comment]
I fixed the problem of not being able to clone the repo recursively by generating and adding the ssh-key to my github account. Even then, I'm seeing the same error.

**Comment by justinkterry** [comment]
I'm also getting this error and don't know why

**Comment by justinkterry** [comment]
Update:
The issue is this code is not compatible with python 3.7, which has been out since June 27, 2018.

```
justinkterry@Prophet:~/Documents/MADRL/rltools/rltools$ flake8 util.py
util.py:37:17: W605 invalid escape sequence '\_'
util.py:37:28: W605 invalid escape sequence '\_'
util.py:59:80: E501 line too long (94 > 79 characters)
util.py:71:80: E501 line too long (101 > 79 characters)
util.py:141:80: E501 line too long (96 > 79 characters)
util.py:142:80: E501 line too long (93 > 79 characters)
util.py:150:80: E501 line too long (93 > 79 characters)
util.py:157:46: W606 'async' and 'await' are reserved keywords starting with Python 3.7
util.py:157:50: E999 SyntaxError: invalid syntax
util.py:164:80: E501 line too long (91 > 79 characters)
util.py:164:80: W606 'async' and 'await' are reserved keywords starting with Python 3.7
util.py:229:80: E501 line too long (96 > 79 characters)
util.py:273:80: E501 line too long (88 > 79 characters)
util.py:274:80: E501 line too long (88 > 79 characters)
```

@rejuvyesh could you please fix this?

**Comment by xiaominy** [comment]
have you fix this problem?

**Comment by jkterry1** [comment]
These environments are all now maintained in pettingzoo (https://www.pettingzoo.ml/sisl)
