### ISSUE TITLE
Shape error of tensorflow

### ISSUE THREAD

**Issue by Aaricis** [sisl/MADRL#23]
I faced this error:
`python3 runners/run_multiwalker.py rllab \--control decentralized \--policy_hidden 100,50,25 \--n_iter 200 \--n_walkers 2 \--batch_size 24000 \--curriculum lessons/multiwalker/env.yaml
[2019-07-09 16:30:31,498] Using NumPy C-API based implementation for BLAS functions.
[2019-07-09 16:30:32,017] From /home/zkg/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "runners/run_multiwalker.py", line 58, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "runners/run_multiwalker.py", line 52, in main
    run(curr)
  File "/home/zkg/MADRL/runners/rurllab.py", line 355, in __call__
    env, policy = rllab_envpolicy_parser(self.env, self.args)
  File "/home/zkg/MADRL/runners/rurllab.py", line 175, in rllab_envpolicy_parser
    min_std=args.min_std, name='policy')
  File "/home/zkg/MADRL/rllab/sandbox/rocky/tf/policies/gaussian_mlp_policy.py", line 133, in __init__
    dist_info_sym = self.dist_info_sym(mean_network.input_layer.input_var, dict())
  File "/home/zkg/MADRL/rllab/sandbox/rocky/tf/policies/gaussian_mlp_policy.py", line 147, in dist_info_sym
    mean_var, std_param_var = L.get_output([self._l_mean, self._l_std_param], obs_var)
  File "/home/zkg/MADRL/rllab/sandbox/rocky/tf/core/layers.py", line 1792, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/zkg/MADRL/rllab/sandbox/rocky/tf/core/layers.py", line 354, in get_output_for
    tile_arg = tf.concat(0, [tf.shape(input)[:ndim - 1], [1]])
  File "/home/zkg/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/zkg/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1254, in concat
    tensor_shape.scalar())
  File "/home/zkg/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible`
How can I fix this problem? Which version of tensorflow  should I use?
Thanks!!!

**Comment by rejuvyesh** [comment]
Please check the tensorflow version. This code is quite old now and likely doesn't work with recent versions of tensorflow.

**Comment by Aaricis** [comment]
Thanks for your reply! 
I have fixed this bug by transforming `tf.concat()` parameters like this 
`net_input = tf.concat( [flat.output, scaled_t_B_1],1)` to `net_input = tf.concat(1, [flat.output, scaled_t_B_1])`
