### ISSUE TITLE
Tensorflow shape error

### ISSUE THREAD

**Issue by YantianZha** [sisl/MADRL#3]
Hello,

I'm using your MADRL code, with tensorflow 1.0. I don't know if you have any idea how to fix this issue? At least I don't know which shape should be correct (the (48, 64) one, or the (?, 32) one). Thank you!

The command I'm running: python run_multiwalker.py rllab --control decentralized --policy_hidden 100,50,25 --n_iter 200 --n_walkers 2 --batch_size 24000 --curriculum lessons/multiwalker/env.yaml

Traceback (most recent call last):
  File "/home/local/yzha3/pycharm-2016.3.2/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/local/yzha3/pycharm-2016.3.2/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/local/yzha3/research/planning/MADRL/runners/run_multiwalker.py", line 52, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "/home/local/yzha3/research/planning/MADRL/runners/run_multiwalker.py", line 48, in main
    run()
  File "/home/local/yzha3/research/planning/MADRL/runners/rurllab.py", line 271, in __call__
    self.algo.train()
  File "/home/local/yzha3/research/planning/MADRL/rllab/sandbox/rocky/tf/algos/batch_polopt.py", line 112, in train
    paths = self.obtain_samples(itr)
  File "/home/local/yzha3/research/planning/MADRL/rllab/sandbox/rocky/tf/algos/batch_polopt.py", line 98, in obtain_samples
    return self.sampler.obtain_samples(itr)
  File "/home/local/yzha3/research/planning/MADRL/rllab/sandbox/rocky/tf/samplers/vectorized_sampler.py", line 57, in obtain_samples
    actions, agent_infos = policy.get_actions(obses)
  File "/home/local/yzha3/research/planning/MADRL/rllab/sandbox/rocky/tf/policies/gaussian_mlp_policy.py", line 170, in get_actions
    means, log_stds = self._f_dist(flat_obs)
  File "/home/local/yzha3/research/planning/MADRL/rllab/sandbox/rocky/tf/misc/tensor_utils.py", line 8, in run
    return sess.run(outputs, feed_dict=dict(list(zip(inputs, input_vals))))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (48, 64) for Tensor u'policy/mean_network/input/input:0', which has shape '(?, 32)'

**Comment by rejuvyesh** [comment]
Hey! Have you tried `rllab3` branch instead. We need to merge it to master.

**Comment by YantianZha** [comment]
Thanks! The problem got resolved.
