### ISSUE TITLE
ImportError: No module named 'gym.monitoring'

### ISSUE THREAD

**Issue by JohnJim0816** [sisl/MADRL#30]
I was using python3.5.4 on MacOS 10.15.4, and gym 0.17.2，but faced with the following problem

```bash
Traceback (most recent call last):
  File "/Users/jj/Desktop/MADRL/runners/run_multiwalker.py", line 10, in <module>
    from madrl_environments.walker.multi_walker import MultiWalkerEnv
  File "/Users/jj/Desktop/MADRL/madrl_environments/__init__.py", line 3, in <module>
    from gym.monitoring.video_recorder import ImageEncoder

ImportError: No module named 'gym.monitoring'
```

some wrong with gym version, but the "rllab/environment.yml" did not mention the gym version, can somebody tell me  ?

**Comment by JohnJim0816** [comment]
solved, first find the file "madrl_environments/__init__.py" at line 3
change:
```python
from gym.monitoring.video_recorder import ImageEncoder
```
to:
```python
from gym.wrappers.monitoring.video_recorder import ImageEncoder
```

**Comment by rejuvyesh** [comment]
Yeah, this code was written for a fairly old version of OpenAI Gym. Glad you found a fix.
