### ISSUE TITLE
proxy.client("set_state", state_str, async=True) syntax error while running code

### ISSUE THREAD

**Issue by xiaominy** [sisl/MADRL#35]
When I try to clone the repo using recursive command, I get the following errors:
git clone --recursive git@github.com:sisl/MADRL.git
Cloning into 'MADRL'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Therefore, I cloned only this repo and cloned the rllab and rltools repo manually and added them to the PYTHONPATH as mentioned. I also installed all depenedencies from environment.yml in rllab.

However, when I run the command:
python3 runners/run_multiwalker.py rllab --control decentralized --policy_hidden 100,50,25 --n_iter 200 --n_walkers 2 --batch_size 24000 --curriculum lessons/multiwalker/env.yaml

I get the following errors:
Traceback (most recent call last):
File "runners/run_multiwalker.py", line 10, in
from madrl_environments.walker.multi_walker import MultiWalkerEnv
File "/Users/anirudhajitani/Downloads/Projects/MADRL/madrl_environments/init.py", line 1, in
from rltools.util import EzPickle, stack_dict_list
File "/Users/anirudhajitani/Downloads/Projects/MADRL/rltools/rltools/util.py", line 157
proxy.client("set_state", state_str, async=True)
^
SyntaxError: invalid syntax

I tried to find the the function client, but the prototype for it is completely different. Can somebody tell me what I am foing wrong?

**Comment by rejuvyesh** [comment]
This repo is no longer maintained. I would recommend taking a look at https://www.pettingzoo.ml/sisl if all you want are the environments. https://github.com/jkterry1/parametersharingmadrl has scripts using ray rllib which have more robust implementations.
