### ISSUE TITLE
Error of calling parallel_sampler

### ISSUE THREAD

**Issue by YantianZha** [sisl/MADRL#4]
Hi,

In ma_sampler.py, the "G.policy.set_param_values(params)" would call a method in parallel_sampler.py, with the line 205: G = _get_scoped_G(G, scope), and the line 7: from rllab.sampler.parallel_sampler import (_get_scoped_G, _worker_set_env_params).

However, I don't see any related method in the parallel_sampler.py. Thank you in advance!
 
Traceback (most recent call last):
  File "/home/yantian/research/MADRL/runners/run_multiwalker.py", line 59, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "/home/yantian/research/MADRL/runners/run_multiwalker.py", line 53, in main
    run(curr)
  File "/home/yantian/research/MADRL/runners/rurllab.py", line 360, in __call__
    algo.curriculum_train(curriculum)
  File "/home/yantian/research/MADRL/rllab/sandbox/rocky/tf/algos/batch_ma_polopt.py", line 146, in curriculum_train
    paths = self.obtain_samples(itr)
  File "/home/yantian/research/MADRL/rllab/sandbox/rocky/tf/algos/batch_ma_polopt.py", line 81, in obtain_samples
    return self.sampler.obtain_samples(itr)
  File "/home/yantian/research/MADRL/rllab/sandbox/rocky/tf/samplers/batch_ma_sampler.py", line 52, in obtain_samples
    scope=self.algo.scope,)
  File "/home/yantian/research/MADRL/rllab/rllab/sampler/ma_sampler.py", line 235, in sample_paths
    [(policy_params, ma_mode, scope)] * singleton_pool.n_parallel)
  File "/home/yantian/research/MADRL/rllab/rllab/sampler/stateful_pool.py", line 83, in run_each
    return [runner(self.G, *args_list[0])]
  File "/home/yantian/research/MADRL/rllab/rllab/sampler/ma_sampler.py", line 210, in _worker_set_policy_params
    G.policy.set_param_values(params)
AttributeError: 'NoneType' object has no attribute 'set_param_values'

**Comment by rejuvyesh** [comment]
Try updating now? Forgot updating the `rllab` submodule.

**Comment by YantianZha** [comment]
Thanks! The problem has been resolved.
