### ISSUE TITLE
Problem in rllab/misc/evaluate.py

### ISSUE THREAD

**Issue by YantianZha** [sisl/MADRL#5]
After taking a look, I resolved this bug by changing the line "return dict(ret=rets, retstd=retsstd, discret=discrets, path_reward=path_reward, retlist=retlist, **dictinfos)" to "return dict(ret=rets, retstd=retsstd, discret=discrets, path_reward=pr, retlist=retlist, **dictinfos)". If I'm wrong please let me know. Thanks!

Traceback (most recent call last):
  File "/home/yantian/research/MADRL/runners/run_multiwalker.py", line 59, in <module>
    main(RunnerParser(ENV_OPTIONS))
  File "/home/yantian/research/MADRL/runners/run_multiwalker.py", line 53, in main
    run(curr)
  File "/home/yantian/research/MADRL/runners/rurllab.py", line 360, in __call__
    algo.curriculum_train(curriculum)
  File "/home/yantian/research/MADRL/rllab/sandbox/rocky/tf/algos/batch_ma_polopt.py", line 175, in curriculum_train
    disc=self.discount)
  File "/home/yantian/research/MADRL/rllab/rllab/misc/evaluate.py", line 83, in evaluate
    return dict(ret=rets, retstd=retsstd, discret=discrets, path_reward=path_reward, retlist=retlist, **dictinfos)
NameError: global name 'path_reward' is not defined

**Comment by etotheipluspi** [comment]
Yep, it was a bug, thanks for the catch. Fixed now.
